# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "pink rhubarb")
Ingredient.create(name: "caster sugar")
Ingredient.create(name: "gin")
Ingredient.create(name: "dark rum")
Ingredient.create(name: "white rum")
Ingredient.create(name: "passion fruit")
Ingredient.create(name: "orange")
Ingredient.create(name: "blueberries")
Ingredient.create(name: "sparkling water")
Ingredient.create(name: "vanilla vodka")
Ingredient.create(name: "passoa")
Ingredient.create(name: "lime juice")
Ingredient.create(name: "sugar syrup")
Ingredient.create(name: "cucumber")
Ingredient.create(name: "small mellons")
Ingredient.create(name: "pomegranate seeds")
Ingredient.create(name: "apple juice")
#Dose.create(description: "1 kg", cocktail: "Rhubarb gin", ingredient: "pink rhubarb" )
#Dose.create(description: "400 gr", cocktail: "Rhubarb gin", ingredient: "caster sugar" )
#Dose.create(description: "800 ml", cocktail: "Rhubarb gin", ingredient: "gin" )
#Dose.create(description: "50 ml", cocktail: "Hurricane cocktail", ingredient: "dark rum" )
#Dose.create(description: "50 ml", cocktail: "Hurricane cocktail", ingredient: "white rum" )
#Dose.create(description: "1", cocktail: "Hurricane cocktail", ingredient: "passion fruit" )
#Dose.create(description: "1", cocktail: "Hurricane cocktail", ingredient: "orange" )
#Dose.create(description: "1", cocktail: "Hurricane cocktail", ingredient: "lemon" )
#Dose.create(description: "50 ml", cocktail: "Hurricane cocktail", ingredient: "sugar syrup" )
#Dose.create(description: "2 tsp", cocktail: "Hurricane cocktail", ingredient: "grenadine" )
#Dose.create(description: "100 gr", cocktail: "Blueberry mojito", ingredient: "blueberries" )
#Dose.create(description: "3", cocktail: "Blueberry mojito", ingredient: "lemon" )
#Dose.create(description: "2 tbsp", cocktail: "Blueberry mojito", ingredient: "caster sugar" )
#Dose.create(description: "2 leaves", cocktail: "Blueberry mojito", ingredient: "mint" )
#Dose.create(description: "350 ml", cocktail: "Blueberry mojito", ingredient: "white rum" )
#Dose.create(description: "2", cocktail: "Passion fruit martini", ingredient: "passion fruit" )
#Dose.create(description: "60 ml", cocktail: "Passion fruit martini", ingredient: "vanilla vodka" )
#Dose.create(description: "30 ml", cocktail: "Passion fruit martini", ingredient: "passoa" )
#Dose.create(description: "1 tbsp", cocktail: "Passion fruit martini", ingredient: "lime juice" )
#Dose.create(description: "1 tbsp", cocktail: "Passion fruit martini", ingredient: "sugar syrup" )
#Dose.create(description: "1", cocktail: "Cucumber, mint & mellon punch", ingredient: "cucumber" )
#Dose.create(description: "small bunch", cocktail: "Cucumber, mint & mellon punch", ingredient: "mint" )
#Dose.create(description: "500 ml", cocktail: "Cucumber, mint & mellon punch", ingredient: "vodka" )
#Dose.create(description: "6", cocktail: "Cucumber, mint & mellon punch", ingredient: "lemon" )
#Dose.create(description: "200 gr", cocktail: "Cucumber, mint & mellon punch", ingredient: "caster sugar" )
#Dose.create(description: "1-2", cocktail: "Cucumber, mint & mellon punch", ingredient: "small mellons" )
#Dose.create(description: "1 L", cocktail: "Cucumber, mint & mellon punch", ingredient: "sparkling water" )
#Dose.create(description: "4 cubes", cocktail: "Eastern breeze", ingredient: "ice" )
#Dose.create(description: "300 ml", cocktail: "Eastern breeze", ingredient: "vodka" )
#Dose.create(description: "24 leaves", cocktail: "Eastern breeze", ingredient: "mint" )
#Dose.create(description: "1", cocktail: "Eastern breeze", ingredient: "pomegranate seeds" )
#Dose.create(description: "600 ml", cocktail: "Eastern breeze", ingredient: "apple juice" )

